// ─── Location-based learning structure ────────────────────────────────────────
// JLPT 레벨 대신 "장소" 단위로 학습을 구조화
// 단어도 장소 기준으로 묶임 → 실전 회화 직결

export interface LocationVocab {
  id: string;
  jp: string;
  reading: string;
  ko: string;
}

export interface LocationConfig {
  id: string;
  name_ko: string;
  name_jp: string;
  thumbnail: string;
  description: string;
  vocab: LocationVocab[];
}

export const STATIC_LOCATIONS: LocationConfig[] = [
  {
    id: 'convenience_store',
    name_ko: '편의점',
    name_jp: 'コンビニ',
    thumbnail: '🏪',
    description: '계산, 봉투, 데우기, 포인트 카드',
    vocab: [
      { id: 'cv_01', jp: '袋', reading: 'ふくろ', ko: '봉투' },
      { id: 'cv_02', jp: '温める', reading: 'あたためる', ko: '데우다' },
      { id: 'cv_03', jp: 'お会計', reading: 'おかいけい', ko: '계산' },
      { id: 'cv_04', jp: 'ポイントカード', reading: 'ポイントカード', ko: '포인트 카드' },
      { id: 'cv_05', jp: '大丈夫', reading: 'だいじょうぶ', ko: '괜찮다' },
      { id: 'cv_06', jp: '一枚', reading: 'いちまい', ko: '한 장' },
      { id: 'cv_07', jp: 'ご利用', reading: 'ごりよう', ko: '이용' },
      { id: 'cv_08', jp: 'お願いします', reading: 'おねがいします', ko: '부탁드려요' },
      { id: 'cv_09', jp: 'レシート', reading: 'レシート', ko: '영수증' },
      { id: 'cv_10', jp: 'おつり', reading: 'おつり', ko: '거스름돈' },
      { id: 'cv_11', jp: '小銭', reading: 'こぜに', ko: '잔돈' },
      { id: 'cv_12', jp: '弁当', reading: 'べんとう', ko: '도시락' },
      { id: 'cv_13', jp: '割り箸', reading: 'わりばし', ko: '일회용 젓가락' },
      { id: 'cv_14', jp: 'セルフレジ', reading: 'セルフレジ', ko: '셀프 계산대' },
      { id: 'cv_15', jp: '電子マネー', reading: 'でんしマネー', ko: '전자화폐' },
      { id: 'cv_16', jp: 'スプーン', reading: 'スプーン', ko: '숟가락' },
      { id: 'cv_17', jp: '冷たい', reading: 'つめたい', ko: '차가운' },
      { id: 'cv_18', jp: '温かい', reading: 'あたたかい', ko: '따뜻한' },
      { id: 'cv_19', jp: '宅配便', reading: 'たくはいびん', ko: '택배' },
      { id: 'cv_20', jp: '現金', reading: 'げんきん', ko: '현금' },
    ],
  },
  {
    id: 'restaurant',
    name_ko: '식당',
    name_jp: 'レストラン',
    thumbnail: '🍜',
    description: '예약, 주문, 웨이팅, 계산',
    vocab: [
      { id: 'rs_01', jp: '予約', reading: 'よやく', ko: '예약' },
      { id: 'rs_02', jp: '注文', reading: 'ちゅうもん', ko: '주문' },
      { id: 'rs_03', jp: 'メニュー', reading: 'メニュー', ko: '메뉴' },
      { id: 'rs_04', jp: 'キャンセル', reading: 'キャンセル', ko: '취소' },
      { id: 'rs_05', jp: '名前', reading: 'なまえ', ko: '이름' },
      { id: 'rs_06', jp: '急用', reading: 'きゅうよう', ko: '급한 일' },
      { id: 'rs_07', jp: '申し訳ない', reading: 'もうしわけない', ko: '죄송하다' },
      { id: 'rs_08', jp: '来店', reading: 'らいてん', ko: '방문' },
      { id: 'rs_09', jp: 'お席', reading: 'おせき', ko: '자리' },
      { id: 'rs_10', jp: '待ち時間', reading: 'まちじかん', ko: '대기 시간' },
      { id: 'rs_11', jp: '何名様', reading: 'なんめいさま', ko: '몇 분' },
      { id: 'rs_12', jp: '禁煙席', reading: 'きんえんせき', ko: '금연석' },
      { id: 'rs_13', jp: 'おすすめ', reading: 'おすすめ', ko: '추천' },
      { id: 'rs_14', jp: 'ラストオーダー', reading: 'ラストオーダー', ko: '라스트오더' },
      { id: 'rs_15', jp: 'お会計', reading: 'おかいけい', ko: '계산' },
      { id: 'rs_16', jp: '別々', reading: 'べつべつ', ko: '따로 계산' },
      { id: 'rs_17', jp: 'アレルギー', reading: 'アレルギー', ko: '알레르기' },
      { id: 'rs_18', jp: 'お冷', reading: 'おひや', ko: '냉수' },
      { id: 'rs_19', jp: '食べ放題', reading: 'たべほうだい', ko: '뷔페·무한리필' },
      { id: 'rs_20', jp: '呼び出し', reading: 'よびだし', ko: '호출' },
    ],
  },
  {
    id: 'hotel',
    name_ko: '호텔',
    name_jp: 'ホテル',
    thumbnail: '🏨',
    description: '프런트, 객실, 추가 요청',
    vocab: [
      { id: 'ht_01', jp: 'フロント', reading: 'フロント', ko: '프런트' },
      { id: 'ht_02', jp: 'タオル', reading: 'タオル', ko: '수건' },
      { id: 'ht_03', jp: '部屋', reading: 'へや', ko: '방' },
      { id: 'ht_04', jp: '追加', reading: 'ついか', ko: '추가' },
      { id: 'ht_05', jp: '枚', reading: 'まい', ko: '장 (조수사)' },
      { id: 'ht_06', jp: '号室', reading: 'ごうしつ', ko: '호실' },
      { id: 'ht_07', jp: '用意する', reading: 'ようしする', ko: '준비하다' },
      { id: 'ht_08', jp: '不便', reading: 'ふべん', ko: '불편' },
      { id: 'ht_09', jp: 'チェックイン', reading: 'チェックイン', ko: '체크인' },
      { id: 'ht_10', jp: 'チェックアウト', reading: 'チェックアウト', ko: '체크아웃' },
      { id: 'ht_11', jp: '朝食', reading: 'ちょうしょく', ko: '조식' },
      { id: 'ht_12', jp: '延泊', reading: 'えんぱく', ko: '연박' },
      { id: 'ht_13', jp: 'クリーニング', reading: 'クリーニング', ko: '세탁' },
      { id: 'ht_14', jp: 'モーニングコール', reading: 'モーニングコール', ko: '모닝콜' },
      { id: 'ht_15', jp: '鍵', reading: 'かぎ', ko: '열쇠·카드키' },
      { id: 'ht_16', jp: '駐車場', reading: 'ちゅうしゃじょう', ko: '주차장' },
      { id: 'ht_17', jp: 'Wi-Fi', reading: 'ワイファイ', ko: '와이파이' },
      { id: 'ht_18', jp: '禁煙', reading: 'きんえん', ko: '금연' },
      { id: 'ht_19', jp: '設備', reading: 'せつび', ko: '시설' },
      { id: 'ht_20', jp: 'ルームサービス', reading: 'ルームサービス', ko: '룸서비스' },
    ],
  },
  {
    id: 'duty_free',
    name_ko: '면세점',
    name_jp: '免税店',
    thumbnail: '🛍️',
    description: '여권 제시, 결제, 서류 서명',
    vocab: [
      { id: 'df_01', jp: '免税', reading: 'めんぜい', ko: '면세' },
      { id: 'df_02', jp: 'パスポート', reading: 'パスポート', ko: '여권' },
      { id: 'df_03', jp: '提示', reading: 'ていじ', ko: '제시' },
      { id: 'df_04', jp: '支払い', reading: 'しはらい', ko: '결제' },
      { id: 'df_05', jp: '領収書', reading: 'りょうしゅうしょ', ko: '영수증' },
      { id: 'df_06', jp: 'サイン', reading: 'サイン', ko: '서명' },
      { id: 'df_07', jp: '現金', reading: 'げんきん', ko: '현금' },
      { id: 'df_08', jp: '保管', reading: 'ほかん', ko: '보관' },
      { id: 'df_09', jp: '割引', reading: 'わりびき', ko: '할인' },
      { id: 'df_10', jp: 'クレジットカード', reading: 'クレジットカード', ko: '신용카드' },
      { id: 'df_11', jp: '限定品', reading: 'げんていひん', ko: '한정품' },
      { id: 'df_12', jp: '在庫', reading: 'ざいこ', ko: '재고' },
      { id: 'df_13', jp: '梱包', reading: 'こんぽう', ko: '포장' },
      { id: 'df_14', jp: '免税手続き', reading: 'めんぜいてつづき', ko: '면세 절차' },
      { id: 'df_15', jp: '合計', reading: 'ごうけい', ko: '합계' },
      { id: 'df_16', jp: '税込み', reading: 'ぜいこみ', ko: '세금 포함' },
      { id: 'df_17', jp: '購入', reading: 'こうにゅう', ko: '구입' },
      { id: 'df_18', jp: '配送', reading: 'はいそう', ko: '배송' },
      { id: 'df_19', jp: 'ブランド', reading: 'ブランド', ko: '브랜드' },
      { id: 'df_20', jp: '本人確認', reading: 'ほんにんかくにん', ko: '본인 확인' },
    ],
  },
];

// ─── Additional locations (unlockable by user) ───────────────────────────────
export const MORE_LOCATIONS: LocationConfig[] = [
  {
    id: 'airport',
    name_ko: '공항',
    name_jp: '空港',
    thumbnail: '✈️',
    description: '탑승 수속, 보안 검사, 환승',
    vocab: [
      { id: 'ap_01', jp: '搭乗口', reading: 'とうじょうぐち', ko: '탑승구' },
      { id: 'ap_02', jp: 'チェックイン', reading: 'チェックイン', ko: '체크인' },
      { id: 'ap_03', jp: '手荷物', reading: 'てにもつ', ko: '수하물' },
      { id: 'ap_04', jp: '出発', reading: 'しゅっぱつ', ko: '출발' },
      { id: 'ap_05', jp: '到着', reading: 'とうちゃく', ko: '도착' },
      { id: 'ap_06', jp: '税関', reading: 'ぜいかん', ko: '세관' },
      { id: 'ap_07', jp: '遅延', reading: 'ちえん', ko: '지연' },
      { id: 'ap_08', jp: '搭乗券', reading: 'とうじょうけん', ko: '탑승권' },
      { id: 'ap_09', jp: '出国審査', reading: 'しゅっこくしんさ', ko: '출국 심사' },
      { id: 'ap_10', jp: '手荷物検査', reading: 'てにもつけんさ', ko: '수하물 검사' },
      { id: 'ap_11', jp: 'ターミナル', reading: 'ターミナル', ko: '터미널' },
      { id: 'ap_12', jp: '乗り継ぎ', reading: 'のりつぎ', ko: '환승' },
      { id: 'ap_13', jp: '預け入れ', reading: 'あずけいれ', ko: '위탁 수하물' },
      { id: 'ap_14', jp: '液体', reading: 'えきたい', ko: '액체류' },
      { id: 'ap_15', jp: '機内持ち込み', reading: 'きないもちこみ', ko: '기내 반입' },
      { id: 'ap_16', jp: 'アナウンス', reading: 'アナウンス', ko: '안내 방송' },
      { id: 'ap_17', jp: '免税店', reading: 'めんぜいてん', ko: '면세점' },
      { id: 'ap_18', jp: '両替', reading: 'りょうがえ', ko: '환전' },
      { id: 'ap_19', jp: '座席', reading: 'ざせき', ko: '좌석' },
      { id: 'ap_20', jp: 'パスポートコントロール', reading: 'パスポートコントロール', ko: '여권 심사' },
    ],
  },
  {
    id: 'pharmacy',
    name_ko: '약국',
    name_jp: '薬局',
    thumbnail: '💊',
    description: '증상 설명, 약 구매, 복용법',
    vocab: [
      { id: 'ph_01', jp: '薬', reading: 'くすり', ko: '약' },
      { id: 'ph_02', jp: '痛み', reading: 'いたみ', ko: '통증' },
      { id: 'ph_03', jp: '熱', reading: 'ねつ', ko: '열' },
      { id: 'ph_04', jp: '処方箋', reading: 'しょほうせん', ko: '처방전' },
      { id: 'ph_05', jp: '飲み方', reading: 'のみかた', ko: '복용법' },
      { id: 'ph_06', jp: '症状', reading: 'しょうじょう', ko: '증상' },
      { id: 'ph_07', jp: '風邪薬', reading: 'かぜぐすり', ko: '감기약' },
      { id: 'ph_08', jp: '副作用', reading: 'ふくさよう', ko: '부작용' },
      { id: 'ph_09', jp: '頭痛薬', reading: 'ずつうやく', ko: '두통약' },
      { id: 'ph_10', jp: '胃薬', reading: 'いぐすり', ko: '위장약' },
      { id: 'ph_11', jp: '目薬', reading: 'めぐすり', ko: '안약' },
      { id: 'ph_12', jp: '湿布', reading: 'しっぷ', ko: '파스' },
      { id: 'ph_13', jp: '一日三回', reading: 'いちにちさんかい', ko: '하루 세 번' },
      { id: 'ph_14', jp: '食後', reading: 'しょくご', ko: '식후' },
      { id: 'ph_15', jp: '食前', reading: 'しょくぜん', ko: '식전' },
      { id: 'ph_16', jp: 'アレルギー', reading: 'アレルギー', ko: '알레르기' },
      { id: 'ph_17', jp: '保険証', reading: 'ほけんしょう', ko: '보험증' },
      { id: 'ph_18', jp: '市販薬', reading: 'しはんやく', ko: '일반의약품' },
      { id: 'ph_19', jp: '冷蔵保存', reading: 'れいぞうほぞん', ko: '냉장 보관' },
      { id: 'ph_20', jp: '効能', reading: 'こうのう', ko: '효능' },
    ],
  },
  {
    id: 'train_station',
    name_ko: '기차역',
    name_jp: '駅',
    thumbnail: '🚆',
    description: '티켓 구매, 환승, 플랫폼',
    vocab: [
      { id: 'tr_01', jp: '切符', reading: 'きっぷ', ko: '티켓' },
      { id: 'tr_02', jp: '乗り換え', reading: 'のりかえ', ko: '환승' },
      { id: 'tr_03', jp: 'ホーム', reading: 'ホーム', ko: '플랫폼' },
      { id: 'tr_04', jp: '終電', reading: 'しゅうでん', ko: '막차' },
      { id: 'tr_05', jp: '改札', reading: 'かいさつ', ko: '개찰구' },
      { id: 'tr_06', jp: '急行', reading: 'きゅうこう', ko: '급행' },
      { id: 'tr_07', jp: '指定席', reading: 'していせき', ko: '지정석' },
      { id: 'tr_08', jp: '定期券', reading: 'ていきけん', ko: '정기권' },
      { id: 'tr_09', jp: '自由席', reading: 'じゆうせき', ko: '자유석' },
      { id: 'tr_10', jp: '往復', reading: 'おうふく', ko: '왕복' },
      { id: 'tr_11', jp: '片道', reading: 'かたみち', ko: '편도' },
      { id: 'tr_12', jp: '時刻表', reading: 'じこくひょう', ko: '시간표' },
      { id: 'tr_13', jp: '遅延', reading: 'ちえん', ko: '지연' },
      { id: 'tr_14', jp: '車両', reading: 'しゃりょう', ko: '차량' },
      { id: 'tr_15', jp: '優先席', reading: 'ゆうせんせき', ko: '우선석' },
      { id: 'tr_16', jp: '振替輸送', reading: 'ふりかえゆそう', ko: '대체 수송' },
      { id: 'tr_17', jp: 'ICカード', reading: 'アイシーカード', ko: '교통카드' },
      { id: 'tr_18', jp: '乗り越し', reading: 'のりこし', ko: '초과 승차' },
      { id: 'tr_19', jp: '窓口', reading: 'まどぐち', ko: '창구' },
      { id: 'tr_20', jp: '精算機', reading: 'せいさんき', ko: '정산기' },
    ],
  },
  {
    id: 'izakaya',
    name_ko: '이자카야',
    name_jp: '居酒屋',
    thumbnail: '🍺',
    description: '주문, 건배, 계산 나누기',
    vocab: [
      { id: 'iz_01', jp: '乾杯', reading: 'かんぱい', ko: '건배' },
      { id: 'iz_02', jp: 'おつまみ', reading: 'おつまみ', ko: '안주' },
      { id: 'iz_03', jp: '割り勘', reading: 'わりかん', ko: '더치페이' },
      { id: 'iz_04', jp: 'おかわり', reading: 'おかわり', ko: '리필' },
      { id: 'iz_05', jp: 'ラストオーダー', reading: 'ラストオーダー', ko: '라스트오더' },
      { id: 'iz_06', jp: 'お通し', reading: 'おとおし', ko: '기본 안주' },
      { id: 'iz_07', jp: '締め', reading: 'しめ', ko: '마무리 음식' },
      { id: 'iz_08', jp: '飲み放題', reading: 'のみほうだい', ko: '무제한 음주' },
      { id: 'iz_09', jp: '生ビール', reading: 'なまビール', ko: '생맥주' },
      { id: 'iz_10', jp: 'ハイボール', reading: 'ハイボール', ko: '하이볼' },
      { id: 'iz_11', jp: '焼き鳥', reading: 'やきとり', ko: '야키토리' },
      { id: 'iz_12', jp: '唐揚げ', reading: 'からあげ', ko: '가라아게' },
      { id: 'iz_13', jp: '店員', reading: 'てんいん', ko: '직원' },
      { id: 'iz_14', jp: '個室', reading: 'こしつ', ko: '개인룸' },
      { id: 'iz_15', jp: '人数', reading: 'にんずう', ko: '인원수' },
      { id: 'iz_16', jp: '禁煙', reading: 'きんえん', ko: '금연' },
      { id: 'iz_17', jp: '喫煙', reading: 'きつえん', ko: '흡연' },
      { id: 'iz_18', jp: 'お通し代', reading: 'おとおしだい', ko: '기본 안주 요금' },
      { id: 'iz_19', jp: 'コース', reading: 'コース', ko: '코스 요리' },
      { id: 'iz_20', jp: '一品料理', reading: 'いっぴんりょうり', ko: '단품 요리' },
    ],
  },
  {
    id: 'hospital',
    name_ko: '병원',
    name_jp: '病院',
    thumbnail: '🏥',
    description: '접수, 진료, 처방',
    vocab: [
      { id: 'hs_01', jp: '受付', reading: 'うけつけ', ko: '접수' },
      { id: 'hs_02', jp: '診察', reading: 'しんさつ', ko: '진찰' },
      { id: 'hs_03', jp: '保険証', reading: 'ほけんしょう', ko: '보험증' },
      { id: 'hs_04', jp: '予約', reading: 'よやく', ko: '예약' },
      { id: 'hs_05', jp: '内科', reading: 'ないか', ko: '내과' },
      { id: 'hs_06', jp: '血圧', reading: 'けつあつ', ko: '혈압' },
      { id: 'hs_07', jp: '検査', reading: 'けんさ', ko: '검사' },
      { id: 'hs_08', jp: '待合室', reading: 'まちあいしつ', ko: '대기실' },
      { id: 'hs_09', jp: '問診票', reading: 'もんしんひょう', ko: '문진표' },
      { id: 'hs_10', jp: '症状', reading: 'しょうじょう', ko: '증상' },
      { id: 'hs_11', jp: '熱がある', reading: 'ねつがある', ko: '열이 있다' },
      { id: 'hs_12', jp: '痛み', reading: 'いたみ', ko: '통증' },
      { id: 'hs_13', jp: 'アレルギー', reading: 'アレルギー', ko: '알레르기' },
      { id: 'hs_14', jp: '処方箋', reading: 'しょほうせん', ko: '처방전' },
      { id: 'hs_15', jp: '診察室', reading: 'しんさつしつ', ko: '진료실' },
      { id: 'hs_16', jp: '入院', reading: 'にゅういん', ko: '입원' },
      { id: 'hs_17', jp: '外来', reading: 'がいらい', ko: '외래' },
      { id: 'hs_18', jp: '救急', reading: 'きゅうきゅう', ko: '응급' },
      { id: 'hs_19', jp: '自己負担', reading: 'じこふたん', ko: '본인 부담' },
      { id: 'hs_20', jp: '領収書', reading: 'りょうしゅうしょ', ko: '영수증' },
    ],
  },
];

export function getAllLocations(): LocationConfig[] {
  return [...STATIC_LOCATIONS, ...MORE_LOCATIONS];
}

export function getLocation(id: string): LocationConfig | undefined {
  return getAllLocations().find((l) => l.id === id);
}
